### ISSUE TITLE
Script to create animation of random walk inside volume and their corresponding projections

### ISSUE THREAD

**Issue by Pragyanstha** [Pragyanstha/rayemb#2]
## Summary
Generate an animation that illustrates a landmark point moving along a trajectory inside the volume, while the heatmap changes accordingly

## Todo
- [x] Setup pyvista for volume rendering
- [x] Generate walk trajectory inside the volume
- [x] Create animation by updating the point position and heatmap
