### ISSUE TITLE
Initialize project page

### ISSUE THREAD

**Issue by Pragyanstha** [Pragyanstha/rayemb#3]
## Summary
Initialize the project page with [this template](https://github.com/eliahuhorwitz/Academic-project-page-template).

## Todo
- [x] Copy the template
- [x] Fill the texts
- [x] Fill the media
- [x] Links
