### ISSUE TITLE
Initialize Demo App

### ISSUE THREAD

**Issue by Pragyanstha** [Pragyanstha/rayemb#5]
## Summary
The demo app for this project.

## Todo
- [x] Init vite project
- [x] Implement pages and modules
- [ ] figure out the model post processing part in js
- [ ] setup CI/CD

**Comment by yuyouxixi** [comment]
Wonderful work！ Looking forward to model training guideline.
